
    <footer>
      <div class="content footer">
        <div class="relatorio">
          <div class="nome">
            <img src="<?php echo base_url()?>public/img/icons/relatorio.svg" alt="">
            <h3>Relatórios</h3>
          </div>

          <div class="clear"></div>

          <a href="#">
            <img src="<?php echo base_url()?>public/img/icons/download.svg">
            Vendas
          </a>

          <a href="#">
            <img src="<?php echo base_url()?>public/img/icons/download.svg">
            Veículos
          </a>

          <a href="#">
            <img src="<?php echo base_url()?>public/img/icons/download.svg">
            Frete
          </a>
        </div>

        <div class="estatisticas">
          <div class="nome">
            <img src="<?php echo base_url()?>public/img/icons/Statistics.svg">
            <h3>Estatísticas</h3>
          </div>
        </div>

        <div class="menu-footer">
          <div class="sobre">
            <h3>Sobre Nós</h3>
            <ul>
              <li><a href="#">Contato</a></li>
              <li><a href="#">Quem somos</a></li>
              <li><a href="estatistica.html">Estatísticas</a></li>
            </ul>
          </div>

          <div class="borderred"></div>

          <div class="servicos">
            <h3>Serviços</h3>
            <ul>
              <li><a href="veiculo.html">Veículos</a></li>
              <li><a href="frete.html">Fretes</a></li>
              <li><a href="#">Relatórios</a></li>
            </ul>
          </div>

          <div class="borderred"></div>

          <div class="redes-sociais">
            <h3>Redes Sociais</h3>
            <a href="#"><img src="<?php echo base_url()?>public/img/icons/facebook.svg"></a>
          </div>
        </div>
      </div>
      <div class="copyright">
        <p>&copy; <b>Loop Soft</b> Internet Serviços LTDA</p>
      </div>
    </footer>