<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>SóDelivery - Veiculos</title>
    <link rel="stylesheet" href="<?php base_url()?>public/css/index.css">
    <link rel="stylesheet" href="<?php base_url()?>public/css/fonts&color.css">
    <link rel="stylesheet" type="text/css" href="<?php echo base_url()?>public/css/mapa&veiculos.css">
    <link rel="shortcut icon" href="<?php echo base_url()?>public/img/logo.png" />
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.0/jquery.min.js"></script>
      <script type="text/javascript" src="<?php echo base_url()?>public/js/map&veiculos.js"></script>
  </head>