 <header>
      <div class="logo-publicidade content">
        <div class="logo">
          <a href="index.html">
            <img src="<?php echo base_url()?>public/img/logo.png" alt="logo Só Delivery">
          </a>
        </div>
        <div class="publicidade none">
          <p style="text-align: center; color: white;
          line-height: 100px; font-size: 18px;
          ">espaço reservado a publicidade</p>
        </div>
      </div>

      <div class="menu-conta">
        <div class="menu-bar">
          <div class="pesquisa">
            <input type="text" id="pesquisa">
            <button type="submit">Buscar</button>
          </div>

          <div class="menu-mobile mobile" >
            <i class="fas fa-bars"></i>
          </div>
          <nav class="none">
            <ul>
              <li>
                <a href="/Sodelivery_app" class="nomarginleft">
                  <div class="icon-menu">
                    <img src="<?php echo base_url()?>public/img/icons/home.svg" alt="icone de frete">
                    <p>Home</p>
                  </div>
                </a>
              </li>
              <li>
                <a href="fretes">
                  <div class="icon-menu">
                    <img src="<?php echo base_url()?>public/img/icons/frete.svg" alt="icone de frete">
                    <p>Frete</p>
                  </div>
                </a>
              </li>
              <li>
                <a href="veiculos">
                  <div class="icon-menu">
                    <img src="<?php echo base_url()?>public/img/icons/truck-front.svg" alt="icone de frete">
                    <p>Veículo</p>
                  </div>
                </a>
              </li>
              <li>
                <a href="empresas">
                  <div class="icon-menu">
                    <img src="<?php echo base_url()?>public/img/icons/empresa.svg" alt="icone de frete">
                    <p>Empresa</p>
                  </div>
                </a>
              </li>
              <li>
                <a href="estatistica.html">
                  <div class="icon-menu">
                    <img src="<?php echo base_url()?>public/img/icons/Statistics.svg" alt="icone de frete">
                    <p>Estatística</p>
                  </div>
                </a>
              </li>
              <li>
                <a href="duvidas.html" id="noborderbottom">
                  <div class="icon-menu">
                    <img src="<?php echo base_url()?>public/img/icons/DUVIDAS.svg" alt="icone de frete">
                    <p>Dúvidas</p>
                  </div>
                </a>
              </li>

            </ul>
          </nav>
        </div>

        <div class="conta">
          <div class="mobile-cadastro">
            <a href="Acesso/administrativo" id="login">
                <img src="<?php echo base_url()?>public/img/icons/login.svg" alt="">
              login
            </a>
          </div>
          <div class="desk-cadastro">
            <a href="administrativo">
                <img src="<?php echo base_url()?>public/img/icons/login.svg" alt="">
                <p>Entre ou cadastre-se</p>
            </a>
          </div>
        </div>
      </div>
    </header>