<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Só Delivery</title>
    <link rel="stylesheet" href="<?php base_url()?>public/css/index.css">
	<link rel="stylesheet" href="<?php base_url()?>public/css/fonts&color.css">
    <link rel="shortcut icon" href="<?php base_url()?>public/img/logo.png" />
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.0/jquery.min.js"></script>
  </head>