

    <footer>
      <div class="content footer">
        <div class="relatorio">
          <div class="nome">
            <img src="public/img/icons/relatorio.svg" alt="">
            <h3>Relatórios</h3>
          </div>

          <div class="clear"></div>

          <a href="#">
            <img src="public/img/icons/download.svg">
            Vendas
          </a>

          <a href="#">
            <img src="public/img/icons/download.svg">
            Veículos
          </a>

          <a href="#">
            <img src="public/img/icons/download.svg">
            Frete
          </a>

          <!-- <a href="#" id="button_relatorio">
            <span>+</span>
            Mostrar mais
          </a> -->
        </div>

        <div class="estatisticas">
          <div class="nome">
            <img src="public/img/icons/Statistics.svg">
            <h3>Estatísticas</h3>
          </div>
          <div class="pieChart pieChart_footer">
            <div id="footer_estatistica" class="charts_pie chart-footer"></div>
            <div class="title-chart_footer title-chart">
              <img src="public/img/letras/vendas_footer.svg" alt="titulo chart">
            </div>
            <div class="pieChart-btn">
              <a class="btn_link" href="estatistica.html">
                <p>Ver Todos</p>
              </a>
            </div>
          </div>
        </div>

        <div class="menu-footer">
          <div class="sobre">
            <h3>Sobre Nós</h3>
            <ul>
              <li><a href="contato.html">Contato</a></li>
              <li><a href="quem-somos.html">Quem somos</a></li>
              <li><a href="estatistica.html">Estatísticas</a></li>
            </ul>
          </div>

          <div class="borderred"></div>

          <div class="servicos">
            <h3>Serviços</h3>
            <ul>
              <li><a href="veiculo.html">Veículos</a></li>
              <li><a href="frete.html">Fretes</a></li>
              
            </ul>
          </div>

          <div class="borderred"></div>

          <div class="redes-sociais">
            
            <div class="container-sociais">
              <a href="https://www.facebook.com/sodeliveryExpress/" target="_blank">
                <img src="public/img/icons/facebook.svg">
              </a>

              <a href="https://www.instagram.com/sodeliveryexpress" target="_blank">
                <img src="public/img/icons/instagram.png">
              </a>

              <a href="https://www.linkedin.com/company/sodeliveryexpress" target="_blank">
                <img src="public/img/icons/linkedin.png">
              </a>

              <a href="https://www.youtube.com/channel/UCb93S1zCUAToY4Da6zLF6_w" target="_blank">
                <img src="public/img/icons/youtube.png">
              </a>
            </div>
          </div>
        </div>
      </div>
      <div class="copyright">
        <p>&copy; <b>Loop Soft</b> Internet Serviços LTDA.</p>
      </div>
    </footer>