<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>SóDelivery - Acessar conta</title>
    <link rel="stylesheet" href="public/css/fonts&color.css">
    <link rel="stylesheet" href="public/css/login.css">
    <link rel="shortcut icon" href="public/img/logo.png" />
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.0/jquery.min.js"></script>
    <script src="public/js/troca_page.js"></script>
  </head>