<head>
		<meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>SóDelivery - Fórum de Dúvidas</title>
		<link rel="stylesheet" href="public/css/charts.css">
    <link rel="stylesheet" href="public/css/index.css">
    <link rel="stylesheet" href="public/css/fonts&color.css">
    <link rel="stylesheet" href="public/css/duvidas.css">
    <link rel="shortcut icon" href="public/img/logo.png" />
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.0/jquery.min.js"></script>
		<script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>
    <script type="text/javascript" src="public/js/charts.js"></script>
	</head>