
    <footer>
      <div class="borderred"></div>
      <div class="footer content">
        <div class="container-3">
          <div class="container-footer">
            <h3>Sobre Nós</h3>

            <ul>
              <li><a href="<?php echo base_url()?>pages/contato">Contato</a></li>
              <li><a href="<?php echo base_url()?>pages/quem-somos">Quem somos</a></li>
              <li><a href="https://www.youtube.com/watch?v=DPB_IVicb7Y">Como funciona</a></li>
              <li><a href="<?php echo base_url()?>pages/estatisticas">Estatísticas</a></li>
            </ul>
          </div>

          <div class="separa"></div>

          <div class="container-footer">
            <h3>Cadastro Empresas</h3>

            <ul>
              <li><a href="<?php echo base_url()?>empresas/cadastrar?type=transportadoras">Transportadoras</a></li>
              <li><a href="<?php echo base_url()?>empresas/cadastrar?type=embarcadoras">Embarcadoras</a></li>
              <li><a href="<?php echo base_url()?>empresas/cadastrar?type=agenciadoras">Agenciadoras</a></li>
              <li><a href="<?php echo base_url()?>empresas/cadastrar?type=distrubuidoras">Distribuidoras</a></li>
              <li><a href="<?php echo base_url()?>empresas/cadastrar?type=comercio">Comércio Local</a></li>
              <li><a href="<?php echo base_url()?>empresas/cadastrar?type=industria">Indústria</a></li>
            </ul>
          </div>

          <div class="separa"></div>

          <div class="container-footer">
            <h3>Cadastro Veículos</h3>
            <ul>
              <li><a href="<?= site_url('Veiculos/cadastrar') ?>?type=caminhesCarretas/#veiculos">Caminhões, Carretas</a></li>
              <li><a href="<?= site_url('Veiculos/cadastrar') ?>?type=ultilitarios#veiculos">Utilitários</a></li>
              <li><a href="<?= site_url('Veiculos/cadastrar') ?>?type=fiorinos#veiculos">Fiorinos</a></li>
              <li><a href="<?= site_url('Veiculos/cadastrar') ?>?type=motos#veiculos">Motos</a></li>
            </ul>
          </div>
        </div>

        <div class="separa"></div>

        <div class="container-isoled">
          <div class="container-footer">
            <h3>Assinantes</h3>

            <ul>
              <li><a href="<?php echo base_url()?>pages/administrativo">Meus Fretes</a></li>
              <li><a href="<?php echo base_url()?>pages/administrativo">Minhas Faturas</a></li>
            </ul>
          </div>

          <div class="separa"></div>

          <div class="container-2">
            <iframe src="https://www.facebook.com/plugins/page.php?href=https%3A%2F%2Fwww.facebook.com%2Fsodeliveryexpress&tabs&width=340&height=121&small_header=true&adapt_container_width=true&hide_cover=false&show_facepile=true&appId" width="340" height="121" style="border:none;overflow:hidden" scrolling="no" frameborder="0" allowTransparency="true" allow="encrypted-media"></iframe>

            <div class="social-midias">
              <a href="https://www.facebook.com/sodeliveryExpress/" target="_blank">
                <img src="<?php echo base_url()?>public/img/icons/facebook-white.png">
              </a>

              <a href="https://www.linkedin.com/company/sodeliveryexpress" target="_blank">
                <img src="<?php echo base_url()?>public/img/icons/linkedin.png">
              </a>

              <a href="https://www.instagram.com/sodeliveryexpress" target="_blank">
                <img src="<?php echo base_url()?>public/img/icons/instagram.png">
              </a>

              <a href="https://www.youtube.com/channel/UCb93S1zCUAToY4Da6zLF6_w">
                <img src="<?php echo base_url()?>public/img/icons/youtube.png">
              </a>

              <a href="skype:sodeliveryofc">
                <img src="<?php echo base_url()?>public/img/icons/skype.svg">
              </a>
            </div>
          </div>
        </div>
      </div>

      <div class="end-footer">
        <p>O uso desse site implica na aceitação dos Termos e Condições das Políticas de privacidade <strong><a href="#">Loop Soft</a></strong> Internet Serviços LTDA &copy; 2019 Só Delivery Express - ME. 2019</p>
        <p><a href="<?php echo base_url() ?>pages/login?6b3c7e24c6afaaaf1c2c61160e25d71b=YWNlc3NvX3Jlc3RyaXRv">Acesso Restrito</a></p>
      </div>
    </footer>
