
    <footer>
      <div class="footer">
        <div class="container-3">
          <div class="container-footer">
            <h3>Sobre Nós</h3>

            <ul>
              <li><a href="contato.html">Contato</a></li>
              <li><a href="quem-somos">Quem somos</a></li>
              <li><a href="#">Como funciona</a></li>
              <li><a href="estatistica.html">Estatísticas</a></li>
            </ul>
          </div>

          <div class="separa"></div>

          <div class="container-footer">
            <h3>Cadastro Empresas</h3>

            <ul>
              <li><a href="contato.html">Transportadoras</a></li>
              <li><a href="quem-somos">Embarcadoras</a></li>
              <li><a href="#">Agenciadoras</a></li>
              <li><a href="estatistica.html">Distribuidoras</a></li>
              <li><a href="estatistica.html">Comércio Local</a></li>
              <li><a href="estatistica.html">Indústria</a></li>
            </ul>
          </div>

          <div class="separa"></div>

          <div class="container-footer">
            <h3>Cadastro Veículos</h3>

            <ul>
              <li><a href="contato.html">Caminhões, Carretas</a></li>
              <li><a href="quem-somos">Utilitários</a></li>
              <li><a href="#">Fiorinos</a></li>
              <li><a href="estatistica.html">Motos  </a></li>
            </ul>
          </div>
        </div>

        <div class="separa"></div>

        <div class="container-isoled">
          <div class="container-footer">
            <h3>Assinantes</h3>

            <ul>
              <li><a href="#">Quero ser Assinante</a></li>
              <li><a href="#">Central do Assinante</a></li>
              <li><a href="#">Meus Fretes</a></li>
              <li><a href="#">Minhas Faturas</a></li>
            </ul>
          </div>

          <div class="separa"></div>

          <div class="container-2">
            <iframe src="https://www.facebook.com/plugins/page.php?href=https%3A%2F%2Fwww.facebook.com%2Fsodeliveryexpress&tabs&width=340&height=121&small_header=true&adapt_container_width=true&hide_cover=false&show_facepile=true&appId" width="340" height="121" style="border:none;overflow:hidden" scrolling="no" frameborder="0" allowTransparency="true" allow="encrypted-media"></iframe>

            <div class="social-midias">
              <a href="https://www.facebook.com/sodeliveryExpress/" target="_blank">
                <img src="<?php echo base_url()?>public/img/icons/facebook-white.png">
              </a>

              <a href="https://www.linkedin.com/company/sodeliveryexpress" target="_blank">
                <img src="<?php echo base_url()?>public/img/icons/linkedin.png">
              </a>

              <a href="https://www.instagram.com/sodeliveryexpress" target="_blank">
                <img src="<?php echo base_url()?>public/img/icons/instagram.png">
              </a>

              <a href="https://www.youtube.com/channel/UCb93S1zCUAToY4Da6zLF6_w">
                <img src="<?php echo base_url()?>public/img/icons/youtube.png">
              </a>
            </div>
          </div>
        </div>
      </div>

      <div class="end-footer">
        <p>O uso desse site implica na aceitação dos Termos e Condições das Políticas de privacidade <strong><a href="#">Loop Soft</a></strong> Internet Serviços LTDA &copy; 2019 Só Delivery Express - ME. 2019</p>
      </div>
    </footer>