<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>SóDelivery - Fretes</title>
    <link rel="stylesheet" href="<?php echo base_url()?>public/css/charts.css">
    <link rel="stylesheet" href="<?php echo base_url()?>public/css/index.css">
    <link rel="stylesheet" href="<?php echo base_url()?>public/css/fonts&color.css">
    <link rel="stylesheet" type="text/css" href="<?php echo base_url()?>public/css/itens_frete_empresa_veiculo.css">
    <link rel="shortcut icon" href="<?php echo base_url()?>public/img/logo.png" />
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.0/jquery.min.js"></script>
    <script src="http://demo.itsolutionstuff.com/plugin/jquery.js"></script>
  </head>
