<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>SóDelivery</title>
    <link rel="stylesheet" href="<?php echo base_url()?>public/css/contato.css">
    <link rel="stylesheet" href="<?php echo base_url()?>public/css/duvidas.css">
    <link rel="stylesheet" href="<?php echo base_url()?>public/css/charts.css">
    <link rel="stylesheet" href="<?php echo base_url()?>public/css/index.css">
    <link rel="stylesheet" href="<?php echo base_url()?>public/css/cadastro.css">
		<link rel="stylesheet" href="<?php echo base_url()?>public/css/fonts&color.css">
    <link rel="shortcut icon" href="<?php echo base_url()?>public/img/logo.png" />
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.0/jquery.min.js"></script>
    <script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>
    <script type="text/javascript" src="<?php echo base_url()?>public/js/charts.js"></script>
  </head>
