<header>
  <div class="logo-config">
    <div class="logo">
      <a href="<?php echo base_url()?>pages/administrativo">
        <img src="<?php echo base_url()?>public/img/logo.png" alt="logo Só delivery">
      </a>
      <h2>Painel Administrativo</h2>
    </div>

    <div class="config">
      <img id="blank" src="<?php echo base_url()?>public/img/icons/settings-work-tool.svg">
      <img src="<?php echo base_url()?>public/img/icons/settings-work-tool-dark.svg">
      <span>Configurações</span>
    </div>
  </div>
</header>
