<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>SóDelivery - Painel Administrativo</title>
  <link rel="stylesheet" href="<?php echo base_url()?>public/css/areaadministrativa.css">
  <link rel="stylesheet" href="<?php echo base_url()?>public/css/cadastro.css">
  <link rel="stylesheet" href="<?php echo base_url()?>public/css/index.css">
  <link rel="stylesheet" href="<?php echo base_url()?>public/css/administrativo.css">
  <link rel="stylesheet" href="<?php echo base_url()?>public/css/fonts&color.css">
  <link rel="shortcut icon" href="<?php echo base_url()?>public/img/logo.png" />
</head>
