 <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>SóDelivery</title>
    <link rel="stylesheet" href="<?php echo base_url()?>public/css/charts.css">
    <link rel="stylesheet" href="<?php echo base_url()?>public/css/index.css">
    <link rel="stylesheet" href="<?php echo base_url()?>public/css/cadastro.css">
  	<link rel="stylesheet" href="<?php echo base_url()?>public/css/fonts&color.css">
    <link rel="stylesheet" type="text/css" href="<?php echo base_url()?>public/css/frete_unico.css">
    <link rel="shortcut icon" href="public/img/logo.png" />
  </head>
