
<header>
  <div class="acima-header">
        <div class="info-contato">
          <a href="mailto:comercial@sodeliveryexpress.co.br" target="_blank">
            <div class="icone-top">
              <img src="<?php echo base_url()?>public/img/icons/email.svg">
              <span>comercial@sodeliveryexpress.com.br</span>
            </div>
          </a>

          <div class="icone-top">
            <img src="<?php echo base_url()?>public/img/icons/telefone.svg">
            <span>11 4216 8169</span>
          </div>

          <a href="https://api.whatsapp.com/send?phone=5511997239032" target="_blank">
            <div class="icone-top">
              <img src="<?php echo base_url()?>public/img/icons/whatsapp.svg">
              <span>11 99723 9032</span>
            </div>
          </a>
          <a href="skype:sodeliveryofc">
            <div class="icone-top">
              <img src="<?php echo base_url()?>public/img/icons/skype-dark.svg">
              <span>sodeliveryofc</span>
            </div>
          </a>
        </div>

        <div class="icone-top-midia">
          <a href="https://www.facebook.com/sodeliveryExpress/" target="_blank">
            <img src="<?php echo base_url()?>public/img/icons/facebook-dark.svg">
          </a>

          <a href="https://www.instagram.com/sodeliveryexpress" target="_blank">
            <img src="<?php echo base_url()?>public/img/icons/instagram-dark.svg">
          </a>

          <a href="https://www.linkedin.com/company/sodeliveryexpress" target="_blank">
            <img src="<?php echo base_url()?>public/img/icons/linkedin-dark.svg">
          </a>

          <a href="https://www.youtube.com/channel/UCb93S1zCUAToY4Da6zLF6_w"  id="border_lateral" target="_blank">
            <img src="<?php echo base_url()?>public/img/icons/youtube-dark.svg">
          </a>
          <a href="skype:sodeliveryofc">
            <img src="<?php echo base_url()?>public/img/icons/skype-dark.svg">
          </a>
        </div>
      </div>
      <div class="logo-publicidade content">
        <div class="logo">
          <a href="<?php echo base_url()?>">
            <img src="<?php echo base_url()?>public/img/logo.png" alt="logo Só Delivery">
          </a>
        </div>
        <div class="publicidade none">
          <p style="text-align: center; color: white;
          line-height: 100px; font-size: 18px;
          ">espaço reservado a publicidade</p>
        </div>
      </div>

      <div class="menu-conta">
        <div class="menu-bar">
          <div id="btn-menu" class="menu-mobile mobile" >
            <img src="<?php echo base_url()?>public/img/icons/menu.svg" alt="botão de menu">
          </div>
          <nav class="none">
            <ul>
              <li class="mobile">
                <a href="<?php echo base_url()?>pages/login" id="login">
                  <div class="icon-menu">
                    <img src="<?php echo base_url()?>public/img/icons/login.svg" alt="">
                    <p>Login</p>
                  </div>
                </a>
              </li>
              <li>
                <a href="<?php echo base_url()?>" class="nomarginleft">
                  <div class="icon-menu">
                    <img src="<?php echo base_url()?>public/img/icons/home.svg" alt="icone de frete">
                    <p>Home</p>
                  </div>
                </a>
              </li>
              <li>
                <a href="<?php echo base_url()?>fretes">
                  <div class="icon-menu">
                    <img src="<?php echo base_url()?>public/img/icons/frete.svg" alt="icone de frete">
                    <p>Frete</p>
                  </div>
                </a>
              </li>
              <li>
                <a href="<?= site_url('Veiculos')?>">
                  <div class="icon-menu">
                    <img src="<?php echo base_url()?>public/img/icons/truck-front.svg" alt="icone de frete">
                    <p>Veículo</p>
                  </div>
                </a>
              </li>
              <li>
                <a href="<?php echo base_url()?>empresas">
                  <div class="icon-menu">
                    <img src="<?php echo base_url()?>public/img/icons/empresa.svg" alt="icone de frete">
                    <p>Empresa</p>
                  </div>
                </a>
              </li>
              <li>
                <a href="<?php echo base_url()?>pages/estatisticas">
                  <div class="icon-menu">
                    <img src="<?php echo base_url()?>public/img/icons/Statistics.svg" alt="icone de frete">
                    <p>Estatística</p>
                  </div>
                </a>
              </li>
              <li>
                <a href="<?php echo base_url()?>pages/duvidas" id="noborderbottom">
                  <div class="icon-menu">
                    <img src="<?php echo base_url()?>public/img/icons/DUVIDAS.svg" alt="icone de frete">
                    <p>Dúvidas</p>
                  </div>
                </a>
              </li>

            </ul>
          </nav>
        </div>

        <div class="conta">
          <div class="mobile-cadastro none">
            <a href="<?php echo base_url()?>pages/login" id="login">
                <img src="<?php echo base_url()?>public/img/icons/login.svg" alt="">
              login
            </a>
          </div>
          <div class="desk-cadastro">
            <a href="<?php echo base_url()?>pages/login">
                <img src="<?php echo base_url()?>public/img/icons/login.svg" alt="">
                <p>Entre ou cadastre-se</p>
            </a>
          </div>
        </div>
      </div>
    </header>
