<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>SóDelivery - Estatística</title>
    <link rel="stylesheet" href="<?php echo base_url()?>public/css/charts.css">
    <link rel="stylesheet" href="<?php echo base_url()?>public/css/estatisticas.css">
    <link rel="stylesheet" href="<?php echo base_url()?>public/css/index.css">
    <link rel="stylesheet" href="<?php echo base_url()?>public/css/fonts&color.css">
    <link rel="shortcut icon" href="<?php echo base_url()?>public/img/logo.png" />
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.3/css/all.css" integrity="sha384-UHRtZLI+pbxtHCWp1t77Bi1L4ZtiqrqD80Kn4Z8NTSRyMA2Fd33n5dQ8lWUE00s/" crossorigin="anonymous">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.0/jquery.min.js"></script>
    <script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>
    <script type="text/javascript" src="<?php echo base_url()?>public/js/charts.js"></script>
  </head>
